version: '3.7'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
    - 3306:3306
    # volumes:
    #   - ./db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'cars'
      MYSQL_USER: 'noroot'
      MYSQL_PASSWORD: 'superpassword'
      MYSQL_ROOT_PASSWORD: 'supersecretroot'
    networks:
      - vpn_db
  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile_back
    volumes:
      - back:/app
    # volumes:
    #   - ./www:/app
    ports:
      - '8000:80'
    networks:
      - vpn_db
      - backend
  migrate:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: Dockerfile_migrate
    volumes:
      - back:/app
    # volumes:
    #   - ./www:/app
    command: php artisan migrate:fresh --force --seed
    networks:
      - vpn_db
  front:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: Dockerfile_front
    ports: 
    - 8080:8080
    # volumes:
    #   - ./www:/app
    networks:
      - backend
networks:
  vpn_db:
  backend:
volumes:
  back:
